version: "3.1"

services:
  db-msg:
    image: postgres:latest
    restart: always
    container_name: postgres-msg
    ports:
      - "5432:5432"
    networks:
      - msg-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    networks:
      - msg-network
    ports:
      - "8080:8080"

networks:
  msg-network:
    driver: bridge